# Generated by Django 3.1.7 on 2021-04-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('website', models.CharField(default='None', max_length=200, primary_key=True, serialize=False)),
                ('username', models.CharField(default='None', max_length=200)),
                ('plan', models.CharField(default='Free', max_length=50)),
            ],
        ),
    ]
