# Generated by Django 3.1.7 on 2021-03-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_name', models.CharField(default='None', max_length=200)),
                ('api_key', models.TextField(default='None')),
                ('code', models.TextField(default='None')),
            ],
        ),
    ]
