# Generated by Django 3.1.7 on 2021-04-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collected', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DC_mail_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='BuildUser', max_length=200)),
                ('website', models.CharField(default='Website', max_length=200)),
                ('trigger_name', models.CharField(default='trigger_name', max_length=200)),
                ('message', models.TextField(default='None')),
                ('promo_code', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='DC_new_subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='BuildUser', max_length=200)),
                ('website', models.CharField(default='Website', max_length=200)),
                ('trigger_name', models.CharField(default='trigger_name', max_length=200)),
                ('message', models.TextField(default='None')),
                ('promo_code', models.TextField(default='None')),
            ],
        ),
        migrations.AddField(
            model_name='ynf_form_list',
            name='website',
            field=models.CharField(default='Website', max_length=200),
        ),
    ]
