# Generated by Django 3.1.7 on 2021-04-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collected', '0004_auto_20210422_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dc_new_subscriber',
            name='name',
        ),
    ]
