# Generated by Django 3.1.7 on 2021-03-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='BuildUser', max_length=200)),
                ('build_name', models.CharField(default='BuildName', max_length=200)),
                ('build', models.TextField(default='<h1>Hi!<h1>')),
            ],
        ),
    ]
