# Generated by Django 3.1.7 on 2021-03-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='None', max_length=200)),
                ('website', models.CharField(default='None', max_length=200)),
            ],
        ),
    ]
