# Generated by Django 3.1.7 on 2021-03-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0003_auto_20210323_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.TextField(default='msfFPRBj3TwoZIJgPWfg-M7B'),
        ),
    ]
