# Generated by Django 3.1.7 on 2021-04-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0007_auto_20210325_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.TextField(default='jSYN7_6Dzb01uEjAvgbEamyw'),
        ),
    ]
