# Generated by Django 3.1.7 on 2021-03-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apikey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='None', max_length=200)),
                ('key_name', models.CharField(default='None', max_length=200)),
                ('website', models.CharField(default='None', max_length=200)),
                ('key', models.TextField(default='None')),
            ],
        ),
    ]
