# Generated by Django 3.1.7 on 2021-03-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0005_auto_20210323_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.TextField(default='56ErbbplIn6HKE-Ru_dEYhgf'),
        ),
    ]
