# Generated by Django 3.1.7 on 2021-04-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0008_auto_20210412_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.TextField(default='VN-Z1VtyZlTXCpz-vTlC00t9'),
        ),
    ]
