# Generated by Django 3.1.7 on 2021-04-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0009_auto_20210414_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.TextField(default='J2B8iI_iS9psNdtEIEyhXA6o'),
        ),
    ]
