# Generated by Django 3.1.7 on 2021-04-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0010_auto_20210414_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.TextField(default='meCcXXz0MGIVOkkF1bUFwylo'),
        ),
    ]
