# Generated by Django 3.1.7 on 2021-04-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0011_auto_20210417_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.TextField(default='ZLt-33g6f7T1q543i-TDn20I'),
        ),
    ]
