# Generated by Django 3.1.7 on 2021-04-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0012_auto_20210422_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.TextField(default='jtz_tRKXxGbch4yBntky7A-f'),
        ),
    ]
