# Generated by Django 3.1.7 on 2021-04-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0013_auto_20210422_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.TextField(default='ogTwkKEito93B3ZpxRC1vrkb'),
        ),
    ]
