# Generated by Django 3.1.7 on 2021-03-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertriggers',
            name='build',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='usertriggers',
            name='trigger_type',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
