# Generated by Django 3.1.7 on 2021-03-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='id',
        ),
        migrations.AlterField(
            model_name='tags',
            name='trigger_name',
            field=models.CharField(default='None', max_length=200, primary_key=True, serialize=False),
        ),
    ]
