# Generated by Django 3.1.7 on 2021-03-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder', '0002_auto_20210323_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('trigger_type', models.CharField(default='None', max_length=200, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='triggers/')),
            ],
        ),
        migrations.CreateModel(
            name='UserTriggers',
            fields=[
                ('name', models.CharField(default='None', max_length=200, primary_key=True, serialize=False)),
                ('limit', models.IntegerField(default='10')),
                ('status', models.CharField(choices=[('EN', 'Enable'), ('DS', 'Disable')], default='EN', max_length=2)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.build')),
                ('trigger_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triggers.triggers')),
            ],
        ),
    ]
